=== collibra/node-jsdoc-toolkit/modified/com.collibra.dgc.core/src/main/resources/com/collibra/dgc/core/authorization/rights.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.collibra.com/glossary/rights/" targetNamespace="http://www.collibra.com/glossary/rights/">
    <simpleType name="SupportedByRoles">
    	<restriction base="string"></restriction>
    </simpleType>
    
    <simpleType name="DependsOn">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="RightCategory">
    	<sequence>
    		<element name="rightCategory" type="tns:RightCategory"
    			minOccurs="0" maxOccurs="unbounded" />
    		<element name="right" type="tns:Right" minOccurs="0"
    			maxOccurs="unbounded" />
    	</sequence>
    	<attribute name="name" type="string" />
    	<attribute name="id" type="string" use="required" />
    	<attribute name="active" type="boolean" default="true"/>
    </complexType>

    <complexType name="Right">
    	<sequence>
    		<element name="supportedByRoles" type="tns:SupportedByRoles" minOccurs="0"  maxOccurs="1"/>
    		<element name="dependsOn" type="tns:DependsOn" minOccurs="0"  maxOccurs="1"/>
    	</sequence>
    	<attribute name="name" type="string"/>
		<attribute name="id" type="string" use="required" />
		<attribute name="light" type="boolean" default="false"/>
		<attribute name="impactOnLock" type="boolean" default="false"/>
		<attribute name="active" type="boolean" default="true"/>
    </complexType>
	
	<complexType name="RightCategories">
		<sequence>
			<element name="rightCategory" type="tns:RightCategory" minOccurs="1"  maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<element name="rightCategories" type="tns:RightCategories"></element>
</schema>

=== collibra/node-jsdoc-toolkit/mod/com.collibra.dgc.core/src/main/resources/com/collibra/dgc/core/authorization/rights.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:rightCategories xmlns:tns="http://www.collibra.com/glossary/rights/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="rights.xsd">
	<!-- Community rights  -->
	<rightCategory id="1" name="Community">
		<right id="customizeconfig" name="CustomizeConfig">
			<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
		</right>
		<right id="11" name="Import">
			<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
			<dependsOn>1814</dependsOn> <!-- Needs permission VOCABULARY_IMPORT for importing into existing vocabularies -->
		</right>
		<right id="12" name="Export">
			<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
		</right>
		<right id="13" name="View" active="false">
			<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
		</right>
		<right id="14" name="Edit">
			<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
		</right>
		<right id="15" name="Rename">
			<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
		</right>
		<right id="16" name="Remove">
			<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
		</right>

		<!-- Sub community -->
		<rightCategory id="17" name="Subcommunity" active="false">
			<right id="171" name="View" active="false">
				<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
			</right>
			<right id="172" name="Add">
				<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
			</right>
			<right id="173" name="Remove">
				<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
			</right>
		</rightCategory>

		<!-- Vocabulary  -->
		<rightCategory id="18" name="Vocabulary">
			<right id="181" name="View" active="false">
				<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
			</right>
			<right id="182" name="Add">
				<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
			</right>
			<right id="183" name="Remove">
				<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
			</right>
			<right id="184" name="Edit">
				<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
			</right>
			
			<!-- Representation -->
			<rightCategory id="rep" name="Representation">
				<right id="rep_lock" name="Lock">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>
				<rightCategory id="rep_concept_type" name="Concept Type">
					<right id="rep_concept_type_update" name="Update">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>
			</rightCategory>

			<!-- Terms -->
			<rightCategory id="185" name="Term">
				<right id="1851" name="View" active="false">
					<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
				</right>
				<right id="1852" name="Add">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>
				<right id="1853" name="Remove">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>
				<right id="1854" name="Edit" impactOnLock="true">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>
				<right id="1855" name="Rename" impactOnLock="true">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>
				<right id="1856" name="Import" impactOnLock="true" active="false">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>
				<right id="1857" name="Export" impactOnLock="true" active="false">
					<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
				</right>

				<!-- Attachments -->
				<rightCategory id="1858" name="Attachments">
					<right id="18581" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="18582" name="Add" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
					<right id="18583" name="Remove" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>

				<!-- Comments  -->
				<rightCategory id="1859" name="Comments">
					<right id="18591" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="18592" name="Add">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="18593" name="Remove" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>

				<!-- History  -->
				<rightCategory id="18510" name="History"  active="false">
					<right id="185101" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="185102" name="Compare" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
					<right id="185103" name="Rollback" impactOnLock="true" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>

				<!-- Members -->
				<rightCategory id="18511" name="Members">
					<right id="185111" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="185112" name="Add">
						<supportedByRoles>Admin,Sysadmin</supportedByRoles>
					</right>
					<right id="185113" name="Remove">
						<supportedByRoles>Admin,Sysadmin</supportedByRoles>
					</right>
					<right id="185114" name="Change Role">
						<supportedByRoles>Admin,Sysadmin</supportedByRoles>
					</right>
				</rightCategory>

				<!-- Concept Type -->
				<rightCategory id="18512" name="Concept Type">
					<right id="185121" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="185122" name="Modify" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>

				<!-- General Concept-->
				<rightCategory id="18513" name="General Concept">
					<right id="185131" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="185132" name="Modify" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>

				<!-- Status -->
				<rightCategory id="18514" name="Status">
					<right id="185141" name="View" >
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="185142" name="Modify"  impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
				</rightCategory>

				<!-- Attributes -->
				<rightCategory id="18515" name="Attribute">
					<right id="185151" name="View" active="false">
						<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
					</right>
					<right id="185152" name="Add" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
					<right id="185153" name="Modify" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>
					<right id="185154" name="Remove" impactOnLock="true">
						<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
					</right>

					<!-- Definition -->
					<rightCategory id="term_definition" name="Definition">
						<right id="1851531" name="View" active="false">
							<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
						</right>
						<right id="1851532" name="Add" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851533" name="Modify" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851534" name="Remove" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
					</rightCategory>

					<!-- Description -->
					<rightCategory id="term_description" name="Description">
						<right id="1851541" name="View" active="false">
							<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
						</right>
						<right id="1851542" name="Add" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851543" name="Modify" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851544" name="Remove" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
					</rightCategory>

					<!-- Example -->
					<rightCategory id="185155" name="Example">
						<right id="1851551" name="View" active="false">
							<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
						</right>
						<right id="1851552" name="Add" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851553" name="Modify" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851554" name="Remove" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
					</rightCategory>

					<!-- Note -->
					<rightCategory id="185156" name="Note">
						<right id="1851561" name="View" active="false">
							<supportedByRoles>Admin,Sysadmin,Steward,Normal</supportedByRoles>
						</right>
						<right id="1851562" name="Add" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851563" name="Modify" impactOnLock="true">
							<supportedByRoles>Admin,Sysadmin,Steward</supportedByRoles>
						</right>
						<right id="1851564" name="Remove" impactOnLock="true">
